version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: red-salary-postgres
    environment:
      POSTGRES_DB: red_salary_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres-data:
